### PR TITLE
Test default-no-freestanding with needed fixes.

### PR DESCRIPTION
**Pull request by keith-packard**
Check to see if the fixes for default-no-freestanding work.

### CODE REVIEW

**Comment by stephanosio2** [comment]
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hal_atmel | https://github.com/zephyrproject-rtos/hal_atmel/commit/f47a9a8b55677b5d03bf7f066f907e6b74c9e57d | https://github.com/zephyrproject-rtos/hal_atmel/commit/5ab43007eda3f380c125f957f03638d2e8d1144d (master) | [zephyrproject-rtos/hal_atmel@f47a9a8b..5ab43007](https://github.com/zephyrproject-rtos/hal_atmel/compare/f47a9a8b55677b5d03bf7f066f907e6b74c9e57d..5ab43007eda3f380c125f957f03638d2e8d1144d) |
| hal_espressif | https://github.com/zephyrproject-rtos/hal_espressif/commit/8ee96508f329c7e59fcbf739f060cf12082dd805 | https://github.com/zephyrproject-rtos/hal_espressif/commit/d7576d0da639acbd9a191a3eb7e4f3f3476c9641 | [zephyrproject-rtos/hal_espressif@8ee96508..d7576d0d](https://github.com/zephyrproject-rtos/hal_espressif/compare/8ee96508f329c7e59fcbf739f060cf12082dd805..d7576d0da639acbd9a191a3eb7e4f3f3476c9641) |
| hal_st | https://github.com/zephyrproject-rtos/hal_st/commit/cccbc24c14decfd3f93959f7b14514536af973c7 | https://github.com/zephyrproject-rtos/hal_st/commit/60b149c2df9b7766737af243d2ee5f8c6bd83804 (master) | [zephyrproject-rtos/hal_st@cccbc24c..60b149c2](https://github.com/zephyrproject-rtos/hal_st/compare/cccbc24c14decfd3f93959f7b14514536af973c7..60b149c2df9b7766737af243d2ee5f8c6bd83804) |
| hal_stm32 | https://github.com/zephyrproject-rtos/hal_stm32/commit/7c511b744fadde3fd197779a93043d27e30b0025 | https://github.com/zephyrproject-rtos/hal_stm32/commit/5c79d0c7c4f7094e19959f0bc542ebc35db44002 (main) | [zephyrproject-rtos/hal_stm32@7c511b74..5c79d0c7](https://github.com/zephyrproject-rtos/hal_stm32/compare/7c511b744fadde3fd197779a93043d27e30b0025..5c79d0c7c4f7094e19959f0bc542ebc35db44002) |
| mbedtls | https://github.com/zephyrproject-rtos/mbedtls/commit/6e166050075688fd3cf3d0cb3fc34a1c52df2496 | https://github.com/zephyrproject-rtos/mbedtls/commit/4e1f66df894dc622da7bcd3884016a6ace08e9ea (zephyr) | [zephyrproject-rtos/mbedtls@6e166050..4e1f66df](https://github.com/zephyrproject-rtos/mbedtls/compare/6e166050075688fd3cf3d0cb3fc34a1c52df2496..4e1f66df894dc622da7bcd3884016a6ace08e9ea) |
| mcuboot | https://github.com/zephyrproject-rtos/mcuboot/commit/59624334748129cb93f096408911a227b0dd64c0 (new-history) | https://github.com/zephyrproject-rtos/mcuboot/commit/143485e35b8da7d234677d8920a28f5ea03f6d09 (main,upstream-sync) | [zephyrproject-rtos/mcuboot@59624334..143485e3](https://github.com/zephyrproject-rtos/mcuboot/compare/59624334748129cb93f096408911a227b0dd64c0..143485e35b8da7d234677d8920a28f5ea03f6d09) |
| nrf_hw_models | https://github.com/zephyrproject-rtos/nrf_hw_models/commit/feb3e555f7745dc4fd0a16403f5d81a7ea7359b0 | https://github.com/zephyrproject-rtos/nrf_hw_models/commit/7078310d522664b1612ebac93240b367c4c96299 | [zephyrproject-rtos/nrf_hw_models@feb3e555..7078310d](https://github.com/zephyrproject-rtos/nrf_hw_models/compare/feb3e555f7745dc4fd0a16403f5d81a7ea7359b0..7078310d522664b1612ebac93240b367c4c96299) |
| trusted-firmware-m | https://github.com/zephyrproject-rtos/trusted-firmware-m/commit/a8313be08816a2ed9d883c6b79fb4e5d2bef81c2 | https://github.com/zephyrproject-rtos/trusted-firmware-m/commit/0e25742e8023a0c823c825fbaf19ea265162cc56 (master) | [zephyrproject-rtos/trusted-firmware-m@a8313be0..0e25742e](https://github.com/zephyrproject-rtos/trusted-firmware-m/compare/a8313be08816a2ed9d883c6b79fb4e5d2bef81c2..0e25742e8023a0c823c825fbaf19ea265162cc56) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

**Comment by dleach02** [comment]
This seems to have a ton of changes and mixed things in it?

**Comment by keith-packard** [comment]
> This seems to have a ton of changes and mixed things in it?

yes, all of the changes needed to allow this to build were supposed to be mixed in, this is not intended for upstream merging. I thought that was an acceptable use of this tree?

**Comment by dleach02** [comment]
Okay. I didn't realize this was going to a different repo/tree. I was walking through my github notifications.

**Comment by keith-packard** [comment]
w00t! Looks like this is all working now.

**Comment by henrikbrixandersen** [comment]
> > This seems to have a ton of changes and mixed things in it?
> 
> yes, all of the changes needed to allow this to build were supposed to be mixed in, this is not intended for upstream merging. I thought that was an acceptable use of this tree?

Tip: if possible, you can submit test PRs against this tree as "draft" - then reviews will not be requested.

**Pull request closed without merging**
